repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks: 
  - id: check-yaml
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: end-of-file-fixer
- repo: https://github.com/bsf/black
rev: v22.10.0
hooks:
- id: black